### ISSUE TITLE
PromptIng Guideline Update

### ISSUE THREAD

**Issue by ankykong** [csvidit/prompts#1]
The prompts should use _User_ instead of _me_ as the conversations are between User and Assistant and I'm guessing this is a System prompt which is a third party. Also, I recommend mentioning these prompts are designed more for GPT as they may work better for GPT when compared to Llama, Claude, etc. :)

**Comment by csvidit** [comment]
Thanks for the recommendations! I had tested the resume prompt using Claude 3 Opus on Perplexity, but you're right, it works much better on GPT-4T
